MovieRama/Controllers/MoviesSetupController.cs
using Microsoft.AspNet.Identity;
using MovieRama.ModelsView.MoviesSetup;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using NHome = MovieRama.ModelsView.Home;

namespace MovieRama.Controllers
{
    [Authorize]
    public class MoviesSetupController : Controller
    {
        // GET: MoviesSetup
        public ActionResult Index()
        {
            //if (!User.Identity.IsAuthenticated)
            //{
            //    return RedirectToAction(nameof(MoviesSetupController.Index), "Home");
            //}

            //
            return View(IndexData.Get(User?.Identity.GetUserId(), Convert.ToString(Request?.QueryString.Get("orderby"))));
        }

        [HttpGet]
        public ViewResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(FormCollection collection)
        {
            string movieTitle = collection?.GetValue(nameof(AppDAL.pocos.Movies.Title))?.AttemptedValue;
            if (string.IsNullOrWhiteSpace(movieTitle))
            {
                throw new HttpException(400, "Title cannot be empty");
            }

            using (var dbc = new AppDAL.AppDataDbContext())
            {
                dbc.Movies.Add(new AppDAL.pocos.Movies()
                {
                    Title = movieTitle,
                    Description = collection.GetValue(nameof(AppDAL.pocos.Movies.Description)).AttemptedValue,
                    UserId = User.Identity.GetUserId()
                });

                try
                {
                    await dbc.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new HttpException(500, $"Could not save data. {ex.Message}");
                }
            }

            return View();
        }

        public async Task<ActionResult> UserDisposition()
        {
            // Get items from query string
            if (!int.TryParse(Convert.ToString(Request.QueryString["movieId"]), out int iRequestMovieId))
            {
                throw new HttpException(400, "Invalid Movie");
            }
            if (!int.TryParse(Convert.ToString(Request.QueryString["value"]), out int iRequestDisposition))
            {
                throw new HttpException(400, "Invalid Disposition");
            }
            //
            var currentUserId = User.Identity.GetUserId();
            //
            using (var dbc = new AppDAL.AppDataDbContext())
            {
                // get user who added requested movie
                var IsFromCurrentUser =
                    dbc.Movies
                    .Where(x => x.Id == iRequestMovieId && x.UserId.Equals(currentUserId))
                    .Any();

                if (IsFromCurrentUser)
                {
                    return RedirectToAction(nameof(Index));
                }

                // Get current user disposition
                try
                {
                    var currentUserDispositionForMovie =
                        dbc.MoviesUsersDisposition
                        .Where(x => x.MovieId == iRequestMovieId && x.UserId.Equals(currentUserId))
                        .First();

                    //
                    currentUserDispositionForMovie.DateTimeSet = DateTime.UtcNow;
                    currentUserDispositionForMovie.MovieId = iRequestMovieId;
                    currentUserDispositionForMovie.UserId = currentUserId;
                    currentUserDispositionForMovie.Like = iRequestDisposition == (int)NHome.Definitions.DispositionResult.Like;
                }
                catch (Exception ex) when (ex is ArgumentNullException || ex is InvalidOperationException)
                {
                    dbc.MoviesUsersDisposition.Add(new AppDAL.pocos.MoviesUsersDisposition()
                    {
                        DateTimeSet = DateTime.UtcNow,
                        MovieId = iRequestMovieId,
                        UserId = currentUserId,
                        Like = iRequestDisposition == (int)NHome.Definitions.DispositionResult.Like,
                    });
                }
                catch (Exception ex)
                {
                    throw new HttpException(500, $"Something went wrong. {ex.Message}");
                }

                //
                try
                {
                    await dbc.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new HttpException(500, $"Could not save data. {ex.Message}");
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ViewResult MoviesByUser(string id)
        {
            var mdl = new ModelsView.MoviesSetup.MoviesByUser();

            mdl.UpdateFromSourceForUser(id, User?.Identity.GetUserId());

            return View(mdl);
        } 
    }
}

MovieRama/Views/MoviesSetup/Add.cshtml
@model AppDAL.pocos.Movies

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>


@using (Html.BeginForm("Add", "MoviesSetup", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add a new Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "Some Error", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MovieRama/Views/MoviesSetup/Index.cshtml
@model IEnumerable<MovieRama.ModelsView.MoviesSetup.Index>
@{
    ViewBag.Title = "User's Home Page";
}

<div class="row">
    @if (Model != null && Model.Count() > 0)
    {
        <h3>Sort by</h3>
        <div>
            <a class="btn btn-default" href="/MoviesSetup/Index/?orderby=@Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.CollectionOrderBy.Likes)">Likes</a>
            <a class="btn btn-default" href="/MoviesSetup/Index/?orderby=@Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.CollectionOrderBy.Hates)">Hates</a>
            <a class="btn btn-default" href="/MoviesSetup/Index/?orderby=@Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.CollectionOrderBy.Date)">Date Added</a>
        </div>
    }
</div>
<br />
<div id="MainContainer" class="row">
    <div id="AvailableMovies" class="col-md-9 panel-group">
        <h3>Available Movies</h3>
        @if (Model == null || Model.Count() == 0)
        {
            <div class="jumbotron">
                <span class="text-info">Sorry... No Movies yet   &#x2639;</span>
                <br />
                <span class="text-success">Perhaps add some ;)</span>
            </div>
        }
        else
        {
            foreach (var item in Model)
            {
                var spanDiff = DateTime.UtcNow - item.Movies.DateAdded;
                var timeSpanStr = string.Empty;
                if (spanDiff.TotalDays > 1)
                {
                    timeSpanStr += string.Format("{0} Days ", spanDiff.Days);
                }
                if (spanDiff.TotalHours > 1)
                {
                    timeSpanStr += string.Format("{0} Hours ", spanDiff.Hours);
                }
                if (spanDiff.TotalMinutes > 1)
                {
                    timeSpanStr += string.Format("{0} Minutes ", spanDiff.Minutes);
                }
                if (spanDiff.TotalSeconds > 1)
                {
                    timeSpanStr += string.Format("{0} Seconds ", spanDiff.Seconds);
                }
                if (string.IsNullOrWhiteSpace(timeSpanStr))
                {
                    timeSpanStr = "unknown post date";
                }
                else
                {
                    timeSpanStr += "ago";
                }

                <div id=@string.Format("divMovie{0}", item.Movies.Id) class="panel panel-info">
                    <div class="panel-heading">@item.Movies.Title</div>
                    <small>
                        Posted by
                        <a href="/MoviesSetup/MoviesByUser/?id=@item.UserId">@item.PostedByUser</a>
                        (@timeSpanStr)
                    </small>
                    <div class="panel-body">@item.Movies.Description</div>

                    <div class="panel-footer">
                        <div>
                            @if (item.FromCurrentUser)
                            {
                                <span id="likesLink">@string.Format("{0} Likes", item.Likes)</span>
                                <span id="likeHatesSeparator">|</span>
                                <span id="hatesLink">@string.Format("{0} Hates", item.Hates)</span>
                            }
                            else
                            {
                                <a id="likesLink" class="glyphicon glyphicon-arrow-up text-success" href="/MoviesSetup/UserDisposition/?movieId=@item.Movies.Id&value=@Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Like)">@string.Format("{0} Likes", item.Likes)</a>
                                <span id="likeHatesSeparator">|</span>
                                <a id="hatesLink" class="glyphicon glyphicon-arrow-down text-warning" href="/MoviesSetup/UserDisposition/?movieId=@item.Movies.Id&value=@Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Hate)">@string.Format("{0} Hates", item.Hates)</a>
                            }
                        </div>
                        <div>
                            @if (!item.FromCurrentUser)
                            {
                                int newDisposition = Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.NotAvailable);
                                string newDispositionTxt = "";
                                string dispositionTxt = "You have not voted this movie";
                                if (item.UserDisposition == Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Like))
                                {
                                    newDisposition = Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Hate);
                                    newDispositionTxt = "UnLike";
                                    dispositionTxt = "You LIKED this movie";
                                }
                                else if (item.UserDisposition == Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Hate))
                                {
                                    newDisposition = Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.Like);
                                    newDispositionTxt = "UnHate";
                                    dispositionTxt = "You HATED this movie";
                                }

                                //
                                <span>@dispositionTxt</span>
                                if (item.UserDisposition == Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.NotAvailable))
                                {
                                    <span class="text-danger">@newDispositionTxt</span>
                                }
                                else
                                {
                                    <span id="likeHatesSeparator">|</span>
                                    <a id="changeDispositionLink" class="glyphicon glyphicon-edit text-info" href="/MoviesSetup/UserDisposition/?movieId=@item.Movies.Id&value=@newDisposition">@newDispositionTxt</a>
                                    @*<a id="removeDispositionLink" class="glyphicon glyphicon-alert text-info" href="/MoviesSetup/UserDisposition/?movieId=@item.Movies.Id&value=Convert.ToInt32(MovieRama.ModelsView.Home.Definitions.DispositionResult.NotAvailable)">Revoke my Vote</a>*@
                                }
                            }
                        </div>
                    </div>
                </div>
            }
        }
    </div>
    <div id="ui_buttons" class="col-md-3">
        <a href="/MoviesSetup/Add" class="btn-lg btn-success">Add a New Movie</a>
    </div>
</div>

MovieRama/Views/MoviesSetup/MoviesByUser.cshtml
@model MovieRama.ModelsView.MoviesSetup.MoviesByUser

@{
    ViewBag.Title = Model.UserName + "'s Home Page";
}

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table table-hover table-responsive">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Date Added
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Movies)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @string.Concat(item.DateAdded.ToLongDateString(), " ", item.DateAdded.ToLongTimeString())
                </td>
                <td></td>
            </tr>
        }
    </tbody>
</table>

<div id="navigational_ui">
    @Html.ActionLink("Back to movies list", "Index", "MoviesSetup")
    <span>|</span>
    <a href="#top">Back to top</a>
</div>